module.exports = {
  purge: ['./**/*.liquid'],
  target: "relaxed",
  prefix: "",
  important: true,
  separator: ":",
  theme: {
    extend: {
      colors: {},
    },
    screens: {
      sm: "576px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
    },
    spacing: {
      px: "1px",
      "0": "0",
      ".5": "0.5rem",
      "1": "1rem",
      "1.5": "1.5rem",
      "2": "2rem",
      "2.5": "2.5rem",
      "3": "3rem",
      "3.5": "3.5rem",
      "4": "4rem",
      "5": "5rem",
      "6": "6rem",
      "7": "7rem",
      "8": "8rem",
      "9": "9rem",
      "10": "10rem",
      "11": "11rem",
      "12": "12rem",
      "g-sm": "3.5rem",
      "g-md": "5rem",
      nav: "60px",
    },
    fontSize: {
      "1.4": "1.4rem",
      "1.6": "1.6rem",
      "1.8": "1.8rem",
      "2": "2rem",
      "2.5": "2.5rem",
      "3": "3rem",
    },
    colors: {
      onoGreen: "#00442A",
      onoPink: "#F5C0AF",
      onoBG: "#FDFAF7",
      onoText: "#272727",
      white: "#FFF",
    },
  },
  corePlugins: {},
  plugins: [],
};
